### ISSUE TITLE
Erro com o dtrx

### ISSUE THREAD

**Issue by FerreiraLari** [FerreiraLari/ex-aula-2-GIT#4]
Em #1 o dtrx precisa do nome do arquivo baixado pelo wget e não o link, acredito que por isso está apresentando erro, favor verificar.

**Comment by mrcrdg** [comment]
Ok, erro encontrado. 
@FerreiraLari 
Favor verificar correção no commit dc2075a65d3d383116e3717769ddc72e17f1f7e9

**Comment by FerreiraLari** [comment]
Ótimo!
