### ISSUE TITLE
Resolver Ex_01

### ISSUE THREAD

**Issue by mrcrdg** [FerreiraLari/ex-aula-2-GIT#5]
Realizar a resolução do exercício:
1. Contabilizar o número de atrasos ocorridos em cada aeroporto, listando o nome do aeroporto em uma coluna e o número de atrasos na segunda coluna (recebendo como parâmetro o ano base).

**Comment by PedroNunes92** [comment]
Resolvida com o commit caa0d88fe2d969f83c1df7116006f9b5f1cddd4f
